import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";
import { LOCALES, PAGE_PATHNAMES, localizeHref } from "../../lib/locale";
import { SITE_URL } from "../../lib/seo";

// public/sitemap.xml is generated by scripts/generate-sitemap.mjs on every
// build; this guards that it lists exactly the site's real, localized URLs.
const xml = readFileSync(resolve(__dirname, "../../public/sitemap.xml"), "utf8");
const entries = [...xml.matchAll(/<url>([\s\S]*?)<\/url>/g)].map(([, body]) => ({
  loc: body.match(/<loc>(.*?)<\/loc>/)?.[1],
  lastmod: body.match(/<lastmod>(.*?)<\/lastmod>/)?.[1],
  alternates: [...body.matchAll(/hreflang="([^"]+)" href="([^"]+)"/g)].map(([, lang, href]) => ({ lang, href })),
}));

describe("sitemap.xml", () => {
  it("minden oldal minden nyelvi változatát pontosan egyszer tartalmazza, a lefordított URL-lel", () => {
    const expected = PAGE_PATHNAMES.flatMap((pathname) =>
      LOCALES.map((locale) => `${SITE_URL}${localizeHref(locale, pathname)}`)
    ).sort();
    expect(entries.map((entry) => entry.loc).sort()).toEqual(expected);
  });

  it("minden bejegyzésnek érvényes lastmod dátuma van", () => {
    for (const entry of entries) {
      expect(entry.lastmod, entry.loc).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it("minden bejegyzés felsorolja a 4 nyelvi változatot és az x-default-ot (magyar)", () => {
    for (const entry of entries) {
      expect(entry.alternates.map((alternate) => alternate.lang)).toEqual([...LOCALES, "x-default"]);
      const xDefault = entry.alternates.find((alternate) => alternate.lang === "x-default");
      expect(xDefault?.href).toContain(`${SITE_URL}/hu`);
    }
  });

  it("a robots.txt a sitemapre mutat", () => {
    const robots = readFileSync(resolve(__dirname, "../../public/robots.txt"), "utf8");
    expect(robots).toContain(`Sitemap: ${SITE_URL}/sitemap.xml`);
  });
});
